# Some extensions
- extensions:
  - default: false # all extension are banned by default
  - name: [ScopedTypeVariables, MultiParamTypeClasses, FlexibleInstances, FlexibleContexts, FunctionalDependencies]

# Warnings I don't like
- ignore: {name: Eta reduce}
- ignore: {name: Use head}                  # head gives a warning
- ignore: {name: Use list comprehension}
- ignore: {name: Use tuple-section}
- ignore: {name: Use list literal pattern, within: [MicroHs.Main]}
- ignore: {name: "Avoid lambda using `infix`", within: [MicroHs.TypeCheck]}

- arguments:
    - --ignore-glob=lib/Data/Foldable1.hs
    - --ignore-glob=lib/MiniPrelude.hs
    - --ignore-glob=lib/Prelude.hs
    - --ignore-glob=lib/gmp/Data/Integer_Type.hs
    - --ignore-glob=mhs/MHSPrelude.hs
    - --ignore-glob=tests/Bang.hs
    - --ignore-glob=tests/MultiIf.hs
    - --ignore-glob=tests/Record.hs
