# Warnings currently triggered by your code
- ignore: {name: "Avoid lambda"} # 17 hints
- ignore: {name: "Avoid lambda using `infix`"} # 23 hints
- ignore: {name: "Collapse lambdas"} # 2 hints
- ignore: {name: "Eta reduce"} # 128 hints
- ignore: {name: "Functor law"} # 1 hint
- ignore: {name: "Fuse foldr/map"} # 3 hints
- ignore: {name: "Fuse mapM_/map"} # 1 hint
- ignore: {name: "Hoist not"} # 4 hints
- ignore: {name: "Move brackets to avoid $"} # 8 hints
- ignore: {name: "Move filter"} # 1 hint
- ignore: {name: "Move guards forward"} # 3 hints
- ignore: {name: "Parenthesize unary negation"} # 4 hints
- ignore: {name: "Redundant $"} # 32 hints
- ignore: {name: "Redundant <$>"} # 1 hint
- ignore: {name: "Redundant =="} # 8 hints
- ignore: {name: "Redundant bracket"} # 122 hints
- ignore: {name: "Redundant compare"} # 1 hint
- ignore: {name: "Redundant if"} # 5 hints
- ignore: {name: "Redundant lambda"} # 20 hints
- ignore: {name: "Redundant list comprehension"} # 3 hints
- ignore: {name: "Redundant pure"} # 1 hint
- ignore: {name: "Redundant return"} # 7 hints
- ignore: {name: "Replace case with maybe"} # 4 hints
- ignore: {name: "Unused LANGUAGE pragma"} # 18 hints
- ignore: {name: "Use $>"} # 1 hint
- ignore: {name: "Use &&"} # 1 hint
- ignore: {name: "Use (,)"} # 1 hint
- ignore: {name: "Use (,,)"} # 1 hint
- ignore: {name: "Use <$>"} # 33 hints
- ignore: {name: "Use >=>"} # 2 hints
- ignore: {name: "Use >>"} # 2 hints
- ignore: {name: "Use any"} # 2 hints
- ignore: {name: "Use bimap"} # 1 hint
- ignore: {name: "Use camelCase"} # 20 hints
- ignore: {name: "Use catMaybes"} # 1 hint
- ignore: {name: "Use concatMap"} # 2 hints
- ignore: {name: "Use const"} # 17 hints
- ignore: {name: "Use elem"} # 1 hint
- ignore: {name: "Use elemIndex"} # 3 hints
- ignore: {name: "Use elemIndices"} # 1 hint
- ignore: {name: "Use error"} # 3 hints
- ignore: {name: "Use even"} # 4 hints
- ignore: {name: "Use exitSuccess"} # 3 hints
- ignore: {name: "Use fewer imports"} # 3 hints
- ignore: {name: "Use find"} # 1 hint
- ignore: {name: "Use first"} # 3 hints
- ignore: {name: "Use fmap"} # 5 hints
- ignore: {name: "Use fold"} # 1 hint
- ignore: {name: "Use foldr"} # 5 hints
- ignore: {name: "Use forM"} # 1 hint
- ignore: {name: "Use fromMaybe"} # 3 hints
- ignore: {name: "Use fst"} # 3 hints
- ignore: {name: "Use getContents"} # 1 hint
- ignore: {name: "Use guards"} # 13 hints
- ignore: {name: "Use head"} # 5 hints
- ignore: {name: "Use id"} # 4 hints
- ignore: {name: "Use infix"} # 21 hints
- ignore: {name: "Use insert"} # 1 hint
- ignore: {name: "Use intercalate"} # 4 hints
- ignore: {name: "Use isAlpha"} # 2 hints
- ignore: {name: "Use isAsciiLower"} # 2 hints
- ignore: {name: "Use isAsciiUpper"} # 1 hint
- ignore: {name: "Use isDigit"} # 2 hints
- ignore: {name: "Use isJust"} # 2 hints
- ignore: {name: "Use isNothing"} # 4 hints
- ignore: {name: "Use isOctDigit"} # 1 hint
- ignore: {name: "Use lambda-case"} # 3 hints
- ignore: {name: "Use lefts"} # 1 hint
- ignore: {name: "Use let"} # 1 hint
- ignore: {name: "Use list comprehension"} # 10 hints
- ignore: {name: "Use list literal"} # 5 hints
- ignore: {name: "Use list literal pattern"} # 6 hints
- ignore: {name: "Use logBase"} # 1 hint
- ignore: {name: "Use map"} # 1 hint
- ignore: {name: "Use map once"} # 1 hint
- ignore: {name: "Use map with tuple-section"} # 3 hints
- ignore: {name: "Use mapAndUnzipM"} # 2 hints
- ignore: {name: "Use mapMaybe"} # 1 hint
- ignore: {name: "Use max"} # 2 hints
- ignore: {name: "Use min"} # 3 hints
- ignore: {name: "Use negate"} # 3 hints
- ignore: {name: "Use newtype instead of data"} # 11 hints
- ignore: {name: "Use notElem"} # 11 hints
- ignore: {name: "Use otherwise"} # 15 hints
- ignore: {name: "Use print"} # 52 hints
- ignore: {name: "Use record patterns"} # 25 hints
- ignore: {name: "Use replicate"} # 1 hint
- ignore: {name: "Use replicateM"} # 1 hint
- ignore: {name: "Use rights"} # 1 hint
- ignore: {name: "Use second"} # 3 hints
- ignore: {name: "Use sequenceA"} # 1 hint
- ignore: {name: "Use show"} # 1 hint
- ignore: {name: "Use shows"} # 22 hints
- ignore: {name: "Use snd"} # 3 hints
- ignore: {name: "Use span"} # 1 hint
- ignore: {name: "Use tan"} # 1 hint
- ignore: {name: "Use traverse"} # 1 hint
- ignore: {name: "Use tuple-section"} # 12 hints
- ignore: {name: "Use typeRep"} # 2 hints
- ignore: {name: "Use uncurry"} # 2 hints
- ignore: {name: "Use unless"} # 20 hints
- ignore: {name: "Use void"} # 12 hints
- ignore: {name: "Use when"} # 1 hint
- ignore: {name: "Use zip"} # 1 hint
- ignore: {name: "Use zipWith"} # 1 hint
- ignore: {name: "Used otherwise as a pattern"} # 1 hint

- arguments:
    - --ignore-glob=lib/Data/Foldable1.hs
    - --ignore-glob=lib/MiniPrelude.hs
    - --ignore-glob=lib/Prelude.hs
    - --ignore-glob=lib/gmp/Data/Integer_Type.hs
    - --ignore-glob=mhs/MHSPrelude.hs
    - --ignore-glob=tests/Bang.hs
    - --ignore-glob=tests/MultiIf.hs
    - --ignore-glob=tests/Record.hs
