# Warnings I don't like
- ignore: {name: Eta reduce}
- ignore: {name: Use head}                  # head gives a warning
- ignore: {name: Use list comprehension}
- ignore: {name: Use tuple-section}
# Some special exceptions
- ignore: {name: Use list literal pattern, within: [MicroHs.Main,System.Console.GetOpt]}
- ignore: {name: "Avoid lambda using `infix`", within: [MicroHs.TypeCheck]}
# Various lib stuff
- ignore: {name: Use fst, within: [Data.Functor]}
- ignore: {name: Use snd, within: [Data.Functor]}
- ignore: {name: Use unless, within: [Control.Applicative,Control.Monad]}
- ignore: {name: "Use >>", within: [Control.Monad]}
- ignore: {name: "Use <$>", within: [Control.Monad]}
- ignore: {name: Use id, within: [Control.Exception.Internal]}
- ignore: {name: Use bimap, within: [Data.Bifunctor]}
- ignore: {name: Use first, within: [Data.Bifunctor]}
- ignore: {name: Use concatMap, within: [Data.ByteString]}
- ignore: {name: Use span, within: [Data.ByteString]}
- ignore: {name: Use isAlpha, within: [Data.Char]}
- ignore: {name: Redundant if, within: [Data.Eq,Data.Ord]}
- ignore: {name: Use logBase, within: [Data.Floating]}
- ignore: {name: Use tan, within: [Data.Floating]}
- ignore: {name: Use fold, within: [Data.Foldable]}
- ignore: {name: Use elem, within: [Data.Foldable]}
- ignore: {name: Use elemIndex, within: [Data.List]}
- ignore: {name: Use elemIndices, within: [Data.List]}
- ignore: {name: Use insert, within: [Data.List]}
- ignore: {name: Use negate, within: [Data.Num]}
- ignore: {name: Use min, within: [Data.Ord]}
- ignore: {name: Use max, within: [Data.Ord]}
- ignore: {name: Use traverse, within: [Data.Traversable]}
- ignore: {name: Use sequenceA, within: [Data.Traversable]}
- ignore: {name: Redundant lambda, within: [Data.Tuple]}
- ignore: {name: Use foldr, within: [Control.Applicative]}
- ignore: {name: Use otherwise, within: [Data.Char,Data.Integer_Type,Data.Int.Instances]}
- ignore: {name: Use guards, within: [Data.Ord,Data.Int.Instances]}
- ignore: {name: Avoid lambda, within: [Data.Functor.Compose]}
- ignore: {name: Use camelCase, within: [Foreign.ForeignPtr,Text.Printf]}

- arguments:
    - --ignore-glob=lib/Data/Foldable1.hs
    - --ignore-glob=lib/MiniPrelude.hs
    - --ignore-glob=lib/Prelude.hs
    - --ignore-glob=lib/gmp/Data/Integer_Type.hs
    - --ignore-glob=mhs/MHSPrelude.hs
    - --ignore-glob=tests/Bang.hs
    - --ignore-glob=tests/MultiIf.hs
    - --ignore-glob=tests/Record.hs
