# Build some hackage packages

name: hackage-ci

on:
  push:
#    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-hackage:
    runs-on: ubuntu-latest
    steps:
    # mhs
    - name: checkout mhs repo
      uses: actions/checkout@v4
      with:
        path: mhs
    - name: make and install mhs
      run: |
        cd mhs
        make minstall
        echo "$HOME/.mcabal/bin" >> "$GITHUB_PATH"

    # array-mhs
    - name: compile and install array-mhs package
      run: |
        mcabal install array

    # containers
    - name: compile and install containers package
      run: |
        mcabal install containers

    # transformers
    - name: compile and install transformers package
      run: |
        mcabal install transformers

    # time
    - name: compile and install time package
      run: |
        mcabal install time

    # malcolm-wallace-universe
    # these have not been uploaded to hackage
    - name: checkout malcolm-wallace-universe repo
      uses: actions/checkout@v4
      with:
        repository: hackage-trustees/malcolm-wallace-universe
        path: malcolm-wallace-universe
    - name: compile and install polyparse
      run: |
        cd malcolm-wallace-universe/polyparse-1.12
        mcabal install
    - name: compile and install hscolour
      run: |
        cd malcolm-wallace-universe/hscolour-1.24.4
        mcabal install
    - name: compile and install cpphs
      run: |
        cd malcolm-wallace-universe/cpphs-1.20.9
        mcabal install

    # mtl-mhs
    - name: compile and install mtl-mhs package
      run: |
        mcabal install mtl

    # pretty
    # not yet uploaded to hackage
    - name: compile and install pretty package
      run: |
        mcabal install --git=http://github.com/haskell/pretty.git pretty

    # parsec
    # patch not merged and uploaded to hackage
    - name: compile and install parsec package
      run: |
        mcabal install --git=http://github.com/augustss/parsec.git parsec

    # splitmix
    - name: compile and install splitmix package
      run: |
        mcabal install splitmix

    # random-mhs
    - name: compile and install random-mhs package
      run: |
        mcabal install random

    # granite
    # not on hackage at all
    - name: checkout granite repo
      uses: actions/checkout@v4
      with:
        repository: mchav/granite
        path: granite
    - name: compile and install granite package
      run: |
        cd granite
        mcabal install

    # split
    - name: compile and install split package
      run: |
        mcabal install split

    # monad-loops
    - name: compile and install monad-loops package
      run: |
        mcabal install monad-loops

    # tagged
    # not uploaded to hackage
    - name: compile and install tagged package
      run: |
        mcabal install --git=http://github.com/ekmett/tagged.git tagged

    # exceptions
    # not uploaded to hackage
    - name: compile and install exceptions package
      run: |
        mcabal install --git=http://github.com/ekmett/exceptions.git exceptions

    # ghc-compat
    - name: compile and install ghc-compat package
      run: |
        mcabal install ghc-compat

    # os-string
    # not merged and uploaded to hackage
    - name: compile and install os-string package
      run: |
        mcabal install --git=http://github.com/augustss/os-string.git os-string

    # filepath
    # not merged and uploaded to hackage
    - name: compile and install filepath package
      run: |
        mcabal install --git=http://github.com/augustss/filepath.git filepath

    # tagsoup
    - name: compile and install tagsoup package
      run: |
        mcabal install tagsoup

    # DONE
    - name: cleanup
      run: |
        rm -rf $HOME/.mcabal
